version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: elecciones
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hi-alsoWm24
    ports:
      - "5433:5432"  # Puerto local cambiado
    networks:
      - elecciones-net

  app:
    build: .
    container_name: elecciones-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - elecciones-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/elecciones
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Hi-alsoWm24

networks:
  elecciones-net: